/* ═══════════════════════════════════════════════════════════════
   AURA MEDICINE DATABASE — 60+ medicines, 12 categories
   Each entry: id, name, category, reviews, suitability, rating,
   risk, effects, symptoms (treated), contraindications,
   interactions, dosage, description, manufacturer, approved
═══════════════════════════════════════════════════════════════ */

export const MEDICINE_CATEGORIES = [
  "Pain & Inflammation",
  "Cardiovascular",
  "Antibiotics",
  "Diabetes",
  "Respiratory",
  "Mental Health",
  "Gastrointestinal",
  "Anticoagulants",
  "Hormonal",
  "Oncology",
  "Neurological",
  "Immunosuppressants",
];

export const MEDICINES_DB = [

  /* ── PAIN & INFLAMMATION ─────────────────────────────────── */
  {
    id: 1, category: "Pain & Inflammation",
    name: "Aspirin", genericName: "Acetylsalicylic Acid",
    reviews: 4820, suitability: 91, rating: 4.5, risk: "LOW",
    manufacturer: "Bayer AG", approved: 1899,
    dosage: "75–325 mg once daily",
    description: "Nonsteroidal anti-inflammatory drug (NSAID) used for pain relief, fever reduction, and antiplatelet therapy.",
    symptoms: ["headache", "mild pain", "fever", "inflammation", "platelet aggregation prevention"],
    effects: ["stomach irritation", "mild nausea", "GI upset", "rare: tinnitus"],
    contraindications: ["active peptic ulcer", "hemophilia", "children under 12 (Reye's syndrome risk)", "aspirin allergy"],
    interactions: ["warfarin (increased bleeding)", "ibuprofen (reduced antiplatelet effect)", "alcohol"],
    sentiment: "positive",
  },
  {
    id: 2, category: "Pain & Inflammation",
    name: "Ibuprofen", genericName: "Ibuprofen",
    reviews: 5670, suitability: 87, rating: 4.3, risk: "LOW",
    manufacturer: "Various (generic)", approved: 1969,
    dosage: "200–800 mg every 4–6 hours, max 3200 mg/day",
    description: "NSAID widely used for pain, fever, and inflammation. Available OTC and prescription strength.",
    symptoms: ["headache", "dental pain", "menstrual cramps", "arthritis", "back pain", "fever", "muscle aches"],
    effects: ["heartburn", "stomach pain", "dizziness", "fluid retention", "elevated blood pressure"],
    contraindications: ["third trimester pregnancy", "severe renal impairment", "active GI bleeding", "heart failure"],
    interactions: ["aspirin", "warfarin", "lithium", "ACE inhibitors", "diuretics"],
    sentiment: "positive",
  },
  {
    id: 3, category: "Pain & Inflammation",
    name: "Paracetamol", genericName: "Acetaminophen",
    reviews: 6210, suitability: 95, rating: 4.8, risk: "LOW",
    manufacturer: "Various (generic)", approved: 1955,
    dosage: "325–1000 mg every 4–6 hours, max 4000 mg/day",
    description: "Safe and effective analgesic and antipyretic. First-line for mild to moderate pain, safe in pregnancy.",
    symptoms: ["headache", "toothache", "fever", "mild to moderate pain", "cold symptoms"],
    effects: ["rare rash", "nausea at high doses", "liver toxicity (overdose)"],
    contraindications: ["severe liver disease", "paracetamol hypersensitivity", "chronic heavy alcohol use"],
    interactions: ["warfarin (high doses)", "alcohol", "isoniazid"],
    sentiment: "positive",
  },
  {
    id: 4, category: "Pain & Inflammation",
    name: "Naproxen", genericName: "Naproxen Sodium",
    reviews: 2340, suitability: 84, rating: 4.1, risk: "LOW",
    manufacturer: "Bayer / Roche", approved: 1976,
    dosage: "220–550 mg twice daily",
    description: "Long-acting NSAID providing 8–12 hour pain relief. Preferred for arthritis and menstrual pain.",
    symptoms: ["arthritis pain", "menstrual cramps", "acute gout", "musculoskeletal pain", "tendinitis"],
    effects: ["dyspepsia", "headache", "drowsiness", "edema", "elevated liver enzymes"],
    contraindications: ["CABG surgery", "severe renal disease", "asthma with NSAID sensitivity"],
    interactions: ["lithium", "methotrexate", "antihypertensives", "SSRIs"],
    sentiment: "positive",
  },
  {
    id: 5, category: "Pain & Inflammation",
    name: "Diclofenac", genericName: "Diclofenac Sodium",
    reviews: 1890, suitability: 79, rating: 3.9, risk: "MEDIUM",
    manufacturer: "Novartis", approved: 1974,
    dosage: "50 mg two or three times daily",
    description: "Potent NSAID used for arthritis, post-surgical pain, and dysmenorrhea. Higher cardiovascular risk than other NSAIDs.",
    symptoms: ["osteoarthritis", "rheumatoid arthritis", "ankylosing spondylitis", "acute gout", "post-op pain"],
    effects: ["GI ulceration", "elevated liver enzymes", "headache", "dizziness", "cardiovascular events"],
    contraindications: ["coronary artery disease", "active peptic ulcer", "severe hepatic impairment"],
    interactions: ["cyclosporine", "methotrexate", "digoxin", "lithium"],
    sentiment: "neutral",
  },
  {
    id: 6, category: "Pain & Inflammation",
    name: "Celecoxib", genericName: "Celecoxib",
    reviews: 1420, suitability: 76, rating: 3.8, risk: "MEDIUM",
    manufacturer: "Pfizer", approved: 1998,
    dosage: "100–200 mg once or twice daily",
    description: "Selective COX-2 inhibitor with lower GI side effects than traditional NSAIDs. Used for arthritis and acute pain.",
    symptoms: ["osteoarthritis", "rheumatoid arthritis", "acute pain", "primary dysmenorrhea", "familial adenomatous polyposis"],
    effects: ["cardiovascular events", "hypertension", "diarrhea", "dyspepsia", "peripheral edema"],
    contraindications: ["sulfonamide allergy", "cardiovascular disease history", "late pregnancy"],
    interactions: ["warfarin", "ACE inhibitors", "fluconazole", "lithium"],
    sentiment: "neutral",
  },
  {
    id: 7, category: "Pain & Inflammation",
    name: "Tramadol", genericName: "Tramadol HCl",
    reviews: 980, suitability: 65, rating: 3.5, risk: "HIGH",
    manufacturer: "Grünenthal", approved: 1995,
    dosage: "50–100 mg every 4–6 hours, max 400 mg/day",
    description: "Centrally acting opioid analgesic for moderate to severe pain. Carries addiction potential.",
    symptoms: ["moderate to severe pain", "chronic pain", "post-operative pain", "neuropathic pain"],
    effects: ["dizziness", "nausea", "constipation", "sweating", "seizure risk", "dependence"],
    contraindications: ["MAOI use within 14 days", "severe respiratory depression", "epilepsy", "suicidal ideation"],
    interactions: ["SSRIs (serotonin syndrome)", "MAOIs", "alcohol", "benzodiazepines", "CNS depressants"],
    sentiment: "negative",
  },

  /* ── CARDIOVASCULAR ──────────────────────────────────────── */
  {
    id: 8, category: "Cardiovascular",
    name: "Lisinopril", genericName: "Lisinopril",
    reviews: 3270, suitability: 82, rating: 4.1, risk: "MEDIUM",
    manufacturer: "AstraZeneca / Merck", approved: 1987,
    dosage: "5–40 mg once daily",
    description: "ACE inhibitor used for hypertension, heart failure, and post-MI cardioprotection.",
    symptoms: ["hypertension", "heart failure", "post-MI management", "diabetic nephropathy", "proteinuria"],
    effects: ["dry cough", "hyperkalemia", "hypotension", "dizziness", "angioedema (rare)"],
    contraindications: ["bilateral renal artery stenosis", "history of angioedema", "pregnancy"],
    interactions: ["potassium supplements", "NSAIDs", "diuretics", "lithium"],
    sentiment: "positive",
  },
  {
    id: 9, category: "Cardiovascular",
    name: "Atorvastatin", genericName: "Atorvastatin Calcium",
    reviews: 4120, suitability: 88, rating: 4.4, risk: "LOW",
    manufacturer: "Pfizer (Lipitor)", approved: 1996,
    dosage: "10–80 mg once daily at bedtime",
    description: "HMG-CoA reductase inhibitor (statin) for lowering LDL cholesterol and cardiovascular risk prevention.",
    symptoms: ["hypercholesterolemia", "dyslipidemia", "cardiovascular disease prevention", "familial hypercholesterolemia"],
    effects: ["muscle pain (myalgia)", "elevated liver enzymes", "nausea", "diarrhea", "rare: rhabdomyolysis"],
    contraindications: ["active liver disease", "pregnancy", "breastfeeding", "unexplained muscle pain"],
    interactions: ["clarithromycin", "itraconazole", "cyclosporine", "gemfibrozil", "niacin"],
    sentiment: "positive",
  },
  {
    id: 10, category: "Cardiovascular",
    name: "Metoprolol", genericName: "Metoprolol Succinate",
    reviews: 2890, suitability: 85, rating: 4.2, risk: "LOW",
    manufacturer: "AstraZeneca", approved: 1978,
    dosage: "25–200 mg once daily (extended release)",
    description: "Selective beta-1 blocker for hypertension, angina, heart failure, and post-MI management.",
    symptoms: ["hypertension", "angina pectoris", "chronic heart failure", "atrial fibrillation", "migraine prevention"],
    effects: ["fatigue", "bradycardia", "cold extremities", "depression", "sexual dysfunction"],
    contraindications: ["severe bradycardia", "cardiogenic shock", "decompensated heart failure", "severe asthma"],
    interactions: ["verapamil", "diltiazem", "clonidine", "insulin (masking hypoglycemia)"],
    sentiment: "positive",
  },
  {
    id: 11, category: "Cardiovascular",
    name: "Amlodipine", genericName: "Amlodipine Besylate",
    reviews: 3540, suitability: 87, rating: 4.3, risk: "LOW",
    manufacturer: "Pfizer (Norvasc)", approved: 1990,
    dosage: "2.5–10 mg once daily",
    description: "Calcium channel blocker for hypertension and stable angina. Well-tolerated long-term.",
    symptoms: ["hypertension", "stable angina", "vasospastic angina", "coronary artery disease"],
    effects: ["peripheral edema (ankles)", "flushing", "palpitations", "dizziness", "headache"],
    contraindications: ["cardiogenic shock", "severe aortic stenosis", "hypersensitivity"],
    interactions: ["simvastatin (dose limit)", "cyclosporine", "tacrolimus"],
    sentiment: "positive",
  },
  {
    id: 12, category: "Cardiovascular",
    name: "Warfarin", genericName: "Warfarin Sodium",
    reviews: 1240, suitability: 61, rating: 3.6, risk: "HIGH",
    manufacturer: "Bristol-Myers Squibb", approved: 1954,
    dosage: "2–10 mg daily (INR-guided)",
    description: "Vitamin K antagonist anticoagulant for thrombosis prevention. Narrow therapeutic index requiring regular monitoring.",
    symptoms: ["DVT prevention", "pulmonary embolism", "atrial fibrillation", "mechanical heart valves", "stroke prevention"],
    effects: ["serious bleeding", "bruising", "hair loss", "skin necrosis (rare)", "purple toe syndrome (rare)"],
    contraindications: ["active bleeding", "pregnancy (teratogenic)", "severe hepatic disease", "recent neurosurgery"],
    interactions: ["aspirin", "NSAIDs", "antibiotics", "amiodarone", "over 200 drug interactions documented"],
    sentiment: "negative",
  },
  {
    id: 13, category: "Cardiovascular",
    name: "Losartan", genericName: "Losartan Potassium",
    reviews: 2760, suitability: 83, rating: 4.2, risk: "LOW",
    manufacturer: "Merck", approved: 1995,
    dosage: "25–100 mg once or twice daily",
    description: "Angiotensin II receptor blocker (ARB) for hypertension, diabetic nephropathy, and heart failure. Better tolerated than ACE inhibitors.",
    symptoms: ["hypertension", "diabetic nephropathy", "heart failure", "stroke prevention in hypertensive LVH"],
    effects: ["dizziness", "hyperkalemia", "renal impairment", "upper respiratory infection", "rare: angioedema"],
    contraindications: ["bilateral renal artery stenosis", "pregnancy", "concurrent ACE inhibitor use"],
    interactions: ["potassium-sparing diuretics", "lithium", "NSAIDs", "rifampin"],
    sentiment: "positive",
  },
  {
    id: 14, category: "Cardiovascular",
    name: "Furosemide", genericName: "Furosemide",
    reviews: 1680, suitability: 74, rating: 3.8, risk: "MEDIUM",
    manufacturer: "Sanofi / generic", approved: 1964,
    dosage: "20–80 mg once or twice daily (oral)",
    description: "Loop diuretic for edema associated with heart failure, liver disease, or renal disease.",
    symptoms: ["edema", "heart failure", "pulmonary edema", "hypertension", "hepatic cirrhosis", "renal disease"],
    effects: ["electrolyte imbalance", "dehydration", "hypotension", "ototoxicity (high doses)", "gout"],
    contraindications: ["anuria", "sulfonamide allergy", "severe electrolyte depletion"],
    interactions: ["aminoglycosides (ototoxicity)", "digoxin (hypokalemia risk)", "lithium", "NSAIDs"],
    sentiment: "neutral",
  },
  {
    id: 15, category: "Cardiovascular",
    name: "Digoxin", genericName: "Digoxin",
    reviews: 760, suitability: 62, rating: 3.5, risk: "HIGH",
    manufacturer: "GlaxoSmithKline", approved: 1954,
    dosage: "0.125–0.25 mg once daily",
    description: "Cardiac glycoside for heart failure and atrial fibrillation rate control. Very narrow therapeutic index.",
    symptoms: ["chronic heart failure", "atrial fibrillation", "atrial flutter", "SVT"],
    effects: ["digoxin toxicity (nausea, vomiting, vision changes)", "bradycardia", "arrhythmias", "hyperkalemia"],
    contraindications: ["Wolff-Parkinson-White syndrome", "ventricular fibrillation", "obstructive cardiomyopathy"],
    interactions: ["amiodarone (toxicity)", "quinidine", "verapamil", "spironolactone", "electrolyte-depleting diuretics"],
    sentiment: "negative",
  },

  /* ── ANTIBIOTICS ─────────────────────────────────────────── */
  {
    id: 16, category: "Antibiotics",
    name: "Amoxicillin", genericName: "Amoxicillin Trihydrate",
    reviews: 5430, suitability: 90, rating: 4.6, risk: "LOW",
    manufacturer: "Various (generic)", approved: 1972,
    dosage: "250–500 mg three times daily (7–14 days)",
    description: "Broad-spectrum penicillin antibiotic for bacterial infections of the ear, nose, throat, skin, and urinary tract.",
    symptoms: ["ear infections", "strep throat", "pneumonia", "UTI", "sinusitis", "skin infections"],
    effects: ["diarrhea", "nausea", "rash", "allergic reaction (5–10%)", "yeast overgrowth"],
    contraindications: ["penicillin allergy", "mononucleosis (rash risk)", "severe renal impairment"],
    interactions: ["warfarin", "oral contraceptives (minor)", "methotrexate", "allopurinol"],
    sentiment: "positive",
  },
  {
    id: 17, category: "Antibiotics",
    name: "Azithromycin", genericName: "Azithromycin Dihydrate",
    reviews: 4120, suitability: 88, rating: 4.4, risk: "LOW",
    manufacturer: "Pfizer (Zithromax)", approved: 1991,
    dosage: "500 mg day 1, then 250 mg days 2–5 (Z-pack)",
    description: "Macrolide antibiotic for respiratory, skin, and sexually transmitted infections. Convenient 5-day regimen.",
    symptoms: ["community-acquired pneumonia", "pharyngitis", "skin infections", "chlamydia", "pertussis"],
    effects: ["nausea", "diarrhea", "abdominal pain", "QT prolongation (rare)", "hearing loss (rare)"],
    contraindications: ["QT prolongation", "macrolide hypersensitivity", "severe liver disease"],
    interactions: ["antacids (absorption)", "warfarin", "digoxin", "colchicine", "QT-prolonging drugs"],
    sentiment: "positive",
  },
  {
    id: 18, category: "Antibiotics",
    name: "Ciprofloxacin", genericName: "Ciprofloxacin HCl",
    reviews: 2870, suitability: 81, rating: 4.0, risk: "MEDIUM",
    manufacturer: "Bayer", approved: 1987,
    dosage: "250–750 mg twice daily (5–14 days)",
    description: "Fluoroquinolone antibiotic for complex UTIs, respiratory and GI infections, anthrax. Rising resistance patterns.",
    symptoms: ["UTI", "acute pyelonephritis", "respiratory infections", "infectious diarrhea", "bone and joint infections"],
    effects: ["nausea", "diarrhea", "headache", "tendon rupture (rare)", "QT prolongation", "CNS effects"],
    contraindications: ["under 18 (cartilage risk)", "myasthenia gravis", "QT prolongation", "fluoroquinolone hypersensitivity"],
    interactions: ["antacids (absorption)", "warfarin", "theophylline", "NSAIDs (seizure risk)", "tizanidine"],
    sentiment: "neutral",
  },
  {
    id: 19, category: "Antibiotics",
    name: "Doxycycline", genericName: "Doxycycline Hyclate",
    reviews: 2140, suitability: 83, rating: 4.1, risk: "LOW",
    manufacturer: "Various (generic)", approved: 1967,
    dosage: "100 mg twice daily",
    description: "Tetracycline antibiotic for acne, respiratory, tick-borne, and sexually transmitted infections.",
    symptoms: ["acne vulgaris", "Lyme disease", "Rocky Mountain spotted fever", "chlamydia", "community pneumonia", "malaria prophylaxis"],
    effects: ["photosensitivity", "nausea", "esophageal irritation", "dental staining (children)", "pseudotumor cerebri"],
    contraindications: ["children under 8", "pregnancy", "severe hepatic impairment"],
    interactions: ["antacids", "dairy products (absorption)", "warfarin", "oral contraceptives", "isotretinoin"],
    sentiment: "positive",
  },
  {
    id: 20, category: "Antibiotics",
    name: "Metronidazole", genericName: "Metronidazole",
    reviews: 1870, suitability: 79, rating: 3.9, risk: "MEDIUM",
    manufacturer: "Various (generic)", approved: 1960,
    dosage: "400–500 mg three times daily (5–10 days)",
    description: "Antibiotic and antiparasitic for anaerobic bacteria, protozoa, and H. pylori eradication.",
    symptoms: ["bacterial vaginosis", "C. difficile infection", "trichomoniasis", "H. pylori", "giardiasis", "dental abscess"],
    effects: ["metallic taste", "nausea", "disulfiram-like reaction with alcohol", "peripheral neuropathy (long-term)", "dark urine"],
    contraindications: ["first trimester pregnancy", "alcohol consumption during treatment", "hypersensitivity"],
    interactions: ["alcohol (severe reaction)", "warfarin", "lithium", "busulfan", "phenobarbital"],
    sentiment: "neutral",
  },
  {
    id: 21, category: "Antibiotics",
    name: "Vancomycin", genericName: "Vancomycin HCl",
    reviews: 640, suitability: 68, rating: 3.7, risk: "HIGH",
    manufacturer: "Eli Lilly / generic", approved: 1958,
    dosage: "15–20 mg/kg IV every 8–12 hours (hospital)",
    description: "Glycopeptide antibiotic — last-resort for MRSA and C. difficile. Requires hospital monitoring.",
    symptoms: ["MRSA infections", "serious gram-positive infections", "endocarditis", "C. difficile (oral)", "septicemia"],
    effects: ["nephrotoxicity", "ototoxicity", "red man syndrome", "thrombophlebitis", "neutropenia"],
    contraindications: ["vancomycin hypersensitivity", "deafness history with other ototoxic drugs"],
    interactions: ["aminoglycosides (nephrotoxicity)", "loop diuretics (ototoxicity)", "anesthetic agents"],
    sentiment: "negative",
  },
  {
    id: 22, category: "Antibiotics",
    name: "Clindamycin", genericName: "Clindamycin HCl",
    reviews: 1230, suitability: 75, rating: 3.8, risk: "MEDIUM",
    manufacturer: "Pfizer / generic", approved: 1970,
    dosage: "150–450 mg every 6 hours",
    description: "Lincosamide antibiotic for serious skin, soft tissue, bone, and anaerobic infections. Significant C. difficile risk.",
    symptoms: ["skin abscesses", "cellulitis", "osteomyelitis", "anaerobic infections", "dental infections", "aspiration pneumonia"],
    effects: ["diarrhea", "C. difficile colitis (serious risk)", "rash", "metallic taste", "nausea"],
    contraindications: ["history of C. difficile or antibiotic-associated colitis", "lincosamide allergy"],
    interactions: ["neuromuscular blockers", "erythromycin (antagonism)", "kaolin-pectin (absorption)"],
    sentiment: "neutral",
  },

  /* ── DIABETES ────────────────────────────────────────────── */
  {
    id: 23, category: "Diabetes",
    name: "Metformin", genericName: "Metformin HCl",
    reviews: 4560, suitability: 86, rating: 4.3, risk: "LOW",
    manufacturer: "Various (generic)", approved: 1994,
    dosage: "500–2000 mg daily in divided doses with meals",
    description: "First-line oral antidiabetic biguanide for Type 2 diabetes. Reduces hepatic glucose production.",
    symptoms: ["type 2 diabetes", "insulin resistance", "pre-diabetes", "PCOS (off-label)", "metabolic syndrome"],
    effects: ["GI upset", "diarrhea", "nausea", "vitamin B12 deficiency (long-term)", "metallic taste", "rare: lactic acidosis"],
    contraindications: ["eGFR < 30", "iodinated contrast imaging", "severe hepatic impairment", "alcohol abuse"],
    interactions: ["alcohol", "iodinated contrast", "cimetidine", "diuretics"],
    sentiment: "positive",
  },
  {
    id: 24, category: "Diabetes",
    name: "Glipizide", genericName: "Glipizide",
    reviews: 1890, suitability: 78, rating: 3.9, risk: "MEDIUM",
    manufacturer: "Pfizer", approved: 1984,
    dosage: "2.5–40 mg daily, 30 minutes before meals",
    description: "Second-generation sulfonylurea stimulating pancreatic insulin secretion for type 2 diabetes.",
    symptoms: ["type 2 diabetes", "fasting hyperglycemia"],
    effects: ["hypoglycemia", "weight gain", "dizziness", "nausea", "skin reactions", "hyponatremia"],
    contraindications: ["type 1 diabetes", "diabetic ketoacidosis", "sulfonamide hypersensitivity", "severe hepatic/renal impairment"],
    interactions: ["fluconazole (hypoglycemia)", "rifampin (reduced effect)", "NSAIDs", "beta-blockers (mask hypoglycemia)", "alcohol"],
    sentiment: "neutral",
  },
  {
    id: 25, category: "Diabetes",
    name: "Sitagliptin", genericName: "Sitagliptin Phosphate",
    reviews: 2230, suitability: 85, rating: 4.2, risk: "LOW",
    manufacturer: "Merck (Januvia)", approved: 2006,
    dosage: "100 mg once daily",
    description: "DPP-4 inhibitor enhancing incretin effect. Weight-neutral with low hypoglycemia risk.",
    symptoms: ["type 2 diabetes", "post-prandial hyperglycemia", "combination therapy"],
    effects: ["nasopharyngitis", "upper respiratory infection", "pancreatitis (rare)", "joint pain", "kidney problems"],
    contraindications: ["type 1 diabetes", "diabetic ketoacidosis", "pancreatitis history"],
    interactions: ["digoxin", "cyclosporine", "insulin/sulfonylureas (hypoglycemia risk)"],
    sentiment: "positive",
  },
  {
    id: 26, category: "Diabetes",
    name: "Empagliflozin", genericName: "Empagliflozin",
    reviews: 1560, suitability: 82, rating: 4.2, risk: "LOW",
    manufacturer: "Boehringer Ingelheim (Jardiance)", approved: 2014,
    dosage: "10–25 mg once daily",
    description: "SGLT2 inhibitor with proven cardiovascular and renal protective effects beyond glycemic control.",
    symptoms: ["type 2 diabetes", "cardiovascular disease reduction", "heart failure", "chronic kidney disease", "hyperglycemia"],
    effects: ["genital mycotic infections", "UTI", "polyuria", "DKA (rare)", "volume depletion", "fracture risk"],
    contraindications: ["eGFR < 20", "recurrent genital infections", "type 1 diabetes", "ketoacidosis history"],
    interactions: ["diuretics (hypotension)", "insulin/sulfonylureas (hypoglycemia)"],
    sentiment: "positive",
  },
  {
    id: 27, category: "Diabetes",
    name: "Insulin Glargine", genericName: "Insulin Glargine",
    reviews: 2870, suitability: 88, rating: 4.5, risk: "MEDIUM",
    manufacturer: "Sanofi (Lantus)", approved: 2000,
    dosage: "Once daily SC injection, dose individualised",
    description: "Long-acting basal insulin analog for type 1 and type 2 diabetes providing 24-hour glucose control.",
    symptoms: ["type 1 diabetes", "type 2 diabetes requiring insulin", "uncontrolled hyperglycemia", "post-pancreatectomy diabetes"],
    effects: ["hypoglycemia", "injection site reactions", "weight gain", "lipodystrophy", "allergic reactions"],
    contraindications: ["hypoglycemia episodes", "hypersensitivity to insulin analogs"],
    interactions: ["alcohol", "beta-blockers (mask hypoglycemia)", "thiazolidinediones", "corticosteroids (counteract)"],
    sentiment: "positive",
  },

  /* ── RESPIRATORY ─────────────────────────────────────────── */
  {
    id: 28, category: "Respiratory",
    name: "Salbutamol", genericName: "Albuterol Sulfate",
    reviews: 3870, suitability: 91, rating: 4.6, risk: "LOW",
    manufacturer: "GlaxoSmithKline (Ventolin)", approved: 1968,
    dosage: "2 puffs (180 mcg) every 4–6 hours as needed",
    description: "Short-acting beta-2 agonist bronchodilator (SABA). First-line rescue inhaler for asthma and COPD.",
    symptoms: ["acute asthma attack", "bronchospasm", "exercise-induced bronchospasm", "COPD exacerbation", "wheezing"],
    effects: ["tremor", "palpitations", "tachycardia", "headache", "hypokalemia (high doses)", "nervousness"],
    contraindications: ["hypersensitivity to albuterol"],
    interactions: ["beta-blockers (antagonism)", "MAOIs", "tricyclic antidepressants", "digoxin"],
    sentiment: "positive",
  },
  {
    id: 29, category: "Respiratory",
    name: "Fluticasone", genericName: "Fluticasone Propionate",
    reviews: 2940, suitability: 88, rating: 4.4, risk: "LOW",
    manufacturer: "GlaxoSmithKline (Flonase)", approved: 1994,
    dosage: "88–440 mcg inhaled twice daily; 50 mcg intranasal",
    description: "Inhaled corticosteroid for long-term asthma control and allergic rhinitis. Reduces airway inflammation.",
    symptoms: ["persistent asthma", "allergic rhinitis", "nasal polyps", "seasonal allergies", "perennial rhinitis"],
    effects: ["oral candidiasis", "dysphonia", "throat irritation", "nasal bleeding (intranasal)", "growth suppression (children)"],
    contraindications: ["active respiratory infections", "status asthmaticus (acute)", "hypersensitivity"],
    interactions: ["ritonavir (Cushing's syndrome)", "ketoconazole (systemic corticosteroid effects)"],
    sentiment: "positive",
  },
  {
    id: 30, category: "Respiratory",
    name: "Tiotropium", genericName: "Tiotropium Bromide",
    reviews: 1670, suitability: 83, rating: 4.1, risk: "LOW",
    manufacturer: "Boehringer Ingelheim (Spiriva)", approved: 2004,
    dosage: "18 mcg inhaled once daily",
    description: "Long-acting anticholinergic bronchodilator (LAMA) for COPD maintenance therapy.",
    symptoms: ["COPD", "chronic bronchitis", "emphysema", "exacerbation prevention", "breathlessness"],
    effects: ["dry mouth", "constipation", "urinary retention", "blurred vision", "tachycardia"],
    contraindications: ["narrow-angle glaucoma", "benign prostatic hyperplasia", "bladder neck obstruction"],
    interactions: ["other anticholinergics", "ipratropium (additive)"],
    sentiment: "positive",
  },
  {
    id: 31, category: "Respiratory",
    name: "Montelukast", genericName: "Montelukast Sodium",
    reviews: 2180, suitability: 85, rating: 4.2, risk: "LOW",
    manufacturer: "Merck (Singulair)", approved: 1998,
    dosage: "10 mg once daily in the evening",
    description: "Leukotriene receptor antagonist for asthma maintenance and allergic rhinitis.",
    symptoms: ["asthma", "allergic rhinitis", "exercise-induced bronchoconstriction", "urticaria"],
    effects: ["headache", "abdominal pain", "fatigue", "neuropsychiatric events (black box: suicidal ideation)", "eosinophilia"],
    contraindications: ["acute asthma attack", "phenylketonuria (chewable tablets)", "serious psychiatric illness history"],
    interactions: ["gemfibrozil (increased exposure)", "rifampin (reduced efficacy)", "phenobarbital"],
    sentiment: "positive",
  },

  /* ── MENTAL HEALTH ───────────────────────────────────────── */
  {
    id: 32, category: "Mental Health",
    name: "Sertraline", genericName: "Sertraline HCl",
    reviews: 4230, suitability: 80, rating: 4.0, risk: "MEDIUM",
    manufacturer: "Pfizer (Zoloft)", approved: 1991,
    dosage: "25–200 mg once daily",
    description: "SSRI antidepressant first-line for depression, anxiety disorders, OCD, PTSD, and panic disorder.",
    symptoms: ["major depressive disorder", "OCD", "PTSD", "social anxiety disorder", "panic disorder", "premenstrual dysphoric disorder"],
    effects: ["nausea", "diarrhea", "insomnia", "sexual dysfunction", "weight changes", "serotonin syndrome (overdose)"],
    contraindications: ["MAOI use within 14 days", "pimozide", "pregnancy (third trimester)", "suicidal ideation in youth"],
    interactions: ["MAOIs", "triptans", "tramadol", "warfarin", "lithium", "linezolid"],
    sentiment: "neutral",
  },
  {
    id: 33, category: "Mental Health",
    name: "Fluoxetine", genericName: "Fluoxetine HCl",
    reviews: 3760, suitability: 79, rating: 3.9, risk: "MEDIUM",
    manufacturer: "Eli Lilly (Prozac)", approved: 1987,
    dosage: "20–80 mg once daily",
    description: "Pioneer SSRI antidepressant with long half-life. Covers depression, bulimia nervosa, OCD.",
    symptoms: ["major depression", "OCD", "bulimia nervosa", "panic disorder", "bipolar depression", "premenstrual syndrome"],
    effects: ["insomnia", "sexual dysfunction", "anxiety (initial)", "weight loss", "serotonin syndrome (overdose)", "hyponatremia"],
    contraindications: ["MAOIs", "thioridazine", "pimozide", "linezolid", "IV methylene blue"],
    interactions: ["MAOIs", "lithium", "tramadol", "clozapine", "tricyclic antidepressants", "warfarin"],
    sentiment: "neutral",
  },
  {
    id: 34, category: "Mental Health",
    name: "Quetiapine", genericName: "Quetiapine Fumarate",
    reviews: 2140, suitability: 71, rating: 3.7, risk: "MEDIUM",
    manufacturer: "AstraZeneca (Seroquel)", approved: 1997,
    dosage: "50–800 mg daily in divided doses",
    description: "Atypical antipsychotic for schizophrenia, bipolar disorder, and adjunct depression therapy.",
    symptoms: ["schizophrenia", "bipolar disorder (manic/depressive)", "major depressive disorder (adjunct)", "generalized anxiety"],
    effects: ["sedation", "weight gain", "metabolic syndrome", "dry mouth", "constipation", "orthostatic hypotension", "tardive dyskinesia"],
    contraindications: ["QT prolongation", "dementia-related psychosis (mortality risk)", "paralytic ileus"],
    interactions: ["CYP3A4 inhibitors (ketoconazole)", "carbamazepine", "alcohol", "QT-prolonging drugs", "levodopa"],
    sentiment: "neutral",
  },
  {
    id: 35, category: "Mental Health",
    name: "Lithium Carbonate", genericName: "Lithium Carbonate",
    reviews: 980, suitability: 65, rating: 3.6, risk: "HIGH",
    manufacturer: "Various (generic)", approved: 1970,
    dosage: "900–1800 mg daily (serum-level guided, target 0.6–1.2 mEq/L)",
    description: "Mood stabilizer gold standard for bipolar disorder. Very narrow therapeutic index requiring regular blood monitoring.",
    symptoms: ["bipolar disorder", "manic episodes", "depression augmentation", "suicidal behavior reduction", "cluster headaches"],
    effects: ["tremor", "polyuria", "weight gain", "thyroid dysfunction", "renal impairment", "lithium toxicity"],
    contraindications: ["severe renal impairment", "dehydration", "sodium depletion", "pregnancy (cardiovascular teratogen)"],
    interactions: ["NSAIDs (toxicity)", "ACE inhibitors", "diuretics (toxicity)", "SSRIs", "antipsychotics"],
    sentiment: "negative",
  },
  {
    id: 36, category: "Mental Health",
    name: "Alprazolam", genericName: "Alprazolam",
    reviews: 1640, suitability: 63, rating: 3.5, risk: "HIGH",
    manufacturer: "Pfizer (Xanax)", approved: 1981,
    dosage: "0.25–0.5 mg three times daily (short-term only)",
    description: "Short-acting benzodiazepine for acute anxiety and panic disorder. High dependence potential limits long-term use.",
    symptoms: ["generalized anxiety disorder", "panic disorder", "social anxiety (short-term)", "acute stress response"],
    effects: ["sedation", "cognitive impairment", "dependence", "withdrawal syndrome", "respiratory depression", "paradoxical aggression"],
    contraindications: ["acute narrow-angle glaucoma", "pregnancy", "severe respiratory insufficiency", "sleep apnea", "myasthenia gravis"],
    interactions: ["opioids (fatal respiratory depression)", "alcohol", "CNS depressants", "CYP3A4 inhibitors", "antifungals"],
    sentiment: "negative",
  },

  /* ── GASTROINTESTINAL ────────────────────────────────────── */
  {
    id: 37, category: "Gastrointestinal",
    name: "Omeprazole", genericName: "Omeprazole",
    reviews: 5120, suitability: 90, rating: 4.5, risk: "LOW",
    manufacturer: "AstraZeneca (Prilosec)", approved: 1989,
    dosage: "20–40 mg once daily before meals",
    description: "Proton pump inhibitor (PPI) for GERD, peptic ulcer disease, and H. pylori eradication.",
    symptoms: ["GERD", "peptic ulcer disease", "Zollinger-Ellison syndrome", "H. pylori eradication", "NSAID-induced ulcer prevention"],
    effects: ["headache", "diarrhea", "nausea", "hypomagnesemia (long-term)", "C. difficile risk", "bone fractures (long-term)"],
    contraindications: ["rilpivirine-containing regimens", "hypersensitivity to PPIs"],
    interactions: ["clopidogrel (reduced effect)", "methotrexate", "HIV medications", "iron absorption"],
    sentiment: "positive",
  },
  {
    id: 38, category: "Gastrointestinal",
    name: "Ondansetron", genericName: "Ondansetron HCl",
    reviews: 2870, suitability: 88, rating: 4.4, risk: "LOW",
    manufacturer: "GlaxoSmithKline (Zofran)", approved: 1991,
    dosage: "4–8 mg every 8 hours (oral); 32 mg max IV/day",
    description: "5-HT3 receptor antagonist antiemetic for chemotherapy, radiation, and post-op nausea/vomiting.",
    symptoms: ["chemotherapy-induced nausea", "radiation-induced nausea", "post-operative nausea", "hyperemesis gravidarum"],
    effects: ["headache", "constipation", "dizziness", "QT prolongation", "serotonin syndrome (rare)", "extrapyramidal effects"],
    contraindications: ["congenital long QT syndrome", "concurrent apomorphine use"],
    interactions: ["apomorphine (severe hypotension)", "QT-prolonging drugs", "tramadol", "SSRIs", "phenytoin"],
    sentiment: "positive",
  },
  {
    id: 39, category: "Gastrointestinal",
    name: "Loperamide", genericName: "Loperamide HCl",
    reviews: 2340, suitability: 88, rating: 4.3, risk: "LOW",
    manufacturer: "Johnson & Johnson (Imodium)", approved: 1976,
    dosage: "4 mg initially, then 2 mg after each loose stool, max 16 mg/day",
    description: "Opioid receptor agonist acting locally in GI tract to reduce intestinal motility. OTC antidiarrheal.",
    symptoms: ["acute diarrhea", "traveler's diarrhea", "IBS-D", "colostomy output management"],
    effects: ["constipation", "abdominal pain", "nausea", "QT prolongation (high doses)", "CNS effects (megadose abuse)"],
    contraindications: ["bloody diarrhea", "infectious diarrhea with fever", "C. difficile colitis", "ileus"],
    interactions: ["ritonavir (increased levels)", "saquinavir (QT prolongation)", "quinidine"],
    sentiment: "positive",
  },
  {
    id: 40, category: "Gastrointestinal",
    name: "Mesalazine", genericName: "Mesalamine",
    reviews: 1240, suitability: 79, rating: 4.0, risk: "MEDIUM",
    manufacturer: "Ferring (Asacol)", approved: 1987,
    dosage: "2.4–4.8 g daily in divided doses",
    description: "Aminosalicylate anti-inflammatory for ulcerative colitis induction and remission maintenance.",
    symptoms: ["ulcerative colitis", "proctitis", "Crohn's disease (mild)", "remission maintenance"],
    effects: ["headache", "abdominal pain", "nausea", "diarrhea", "nephrotoxicity (rare)", "rare: acute intolerance syndrome"],
    contraindications: ["salicylate hypersensitivity", "severe renal impairment", "severe hepatic impairment"],
    interactions: ["azathioprine (myelosuppression)", "warfarin", "methotrexate", "digoxin (reduced absorption)"],
    sentiment: "positive",
  },

  /* ── HORMONAL ────────────────────────────────────────────── */
  {
    id: 41, category: "Hormonal",
    name: "Levothyroxine", genericName: "Levothyroxine Sodium",
    reviews: 4890, suitability: 91, rating: 4.6, risk: "LOW",
    manufacturer: "AbbVie (Synthroid)", approved: 1962,
    dosage: "1.6–2.0 mcg/kg/day (TSH-guided)",
    description: "Synthetic T4 hormone replacement for hypothyroidism. Most prescribed medication globally.",
    symptoms: ["hypothyroidism", "Hashimoto's thyroiditis", "thyroid cancer (post-surgery)", "goiter", "myxedema"],
    effects: ["if over-replaced: palpitations, weight loss, heat intolerance, tremor, bone loss", "interactions affect absorption"],
    contraindications: ["thyrotoxicosis", "uncorrected adrenal insufficiency", "cardiac conditions (use with caution)"],
    interactions: ["calcium (absorption)", "iron supplements", "PPIs", "antacids", "cholestyramine", "warfarin"],
    sentiment: "positive",
  },
  {
    id: 42, category: "Hormonal",
    name: "Combined OCP", genericName: "Ethinyl Estradiol / Levonorgestrel",
    reviews: 5630, suitability: 82, rating: 4.2, risk: "MEDIUM",
    manufacturer: "Bayer (Microgynon)", approved: 1960,
    dosage: "1 tablet daily for 21 days, 7-day break",
    description: "Combined oral contraceptive pill for contraception, dysmenorrhea, PCOS, and endometriosis management.",
    symptoms: ["contraception", "dysmenorrhea", "endometriosis", "PCOS", "premenstrual syndrome", "acne"],
    effects: ["nausea", "breast tenderness", "mood changes", "spotting", "VTE risk (3–4× increase)", "hypertension"],
    contraindications: ["migraine with aura", "smoking over 35", "history of VTE", "breast cancer", "hepatic disease"],
    interactions: ["rifampin (contraceptive failure)", "some antiepileptics", "St John's Wort", "ritonavir"],
    sentiment: "positive",
  },
  {
    id: 43, category: "Hormonal",
    name: "Prednisolone", genericName: "Prednisolone Sodium Phosphate",
    reviews: 2340, suitability: 71, rating: 3.7, risk: "MEDIUM",
    manufacturer: "Various (generic)", approved: 1955,
    dosage: "5–60 mg daily (dose and duration vary by condition)",
    description: "Synthetic corticosteroid with potent anti-inflammatory and immunosuppressive activity.",
    symptoms: ["severe asthma", "rheumatoid arthritis", "inflammatory bowel disease", "autoimmune disease", "anaphylaxis", "lymphoma"],
    effects: ["weight gain", "hyperglycemia", "osteoporosis", "adrenal suppression", "infection susceptibility", "mood changes", "cataracts"],
    contraindications: ["systemic fungal infections", "live vaccines during high-dose therapy"],
    interactions: ["NSAIDs (GI ulceration)", "vaccines (live)", "antidiabetics (counteract)", "anticoagulants"],
    sentiment: "neutral",
  },

  /* ── ONCOLOGY ────────────────────────────────────────────── */
  {
    id: 44, category: "Oncology",
    name: "Tamoxifen", genericName: "Tamoxifen Citrate",
    reviews: 1870, suitability: 73, rating: 3.8, risk: "MEDIUM",
    manufacturer: "AstraZeneca (Nolvadex)", approved: 1977,
    dosage: "20 mg once daily for 5–10 years",
    description: "Selective estrogen receptor modulator (SERM) for ER-positive breast cancer adjuvant therapy.",
    symptoms: ["breast cancer (ER+)", "breast cancer prevention", "DCIS", "male breast cancer"],
    effects: ["hot flashes", "vaginal dryness/discharge", "mood changes", "DVT/PE risk", "endometrial cancer risk", "cataracts"],
    contraindications: ["pregnancy", "history of DVT/PE", "concurrent strong CYP2D6 inhibitors"],
    interactions: ["fluoxetine/paroxetine (reduced efficacy)", "warfarin", "rifampin (reduced efficacy)", "aromatase inhibitors"],
    sentiment: "neutral",
  },
  {
    id: 45, category: "Oncology",
    name: "Imatinib", genericName: "Imatinib Mesylate",
    reviews: 760, suitability: 75, rating: 4.0, risk: "HIGH",
    manufacturer: "Novartis (Gleevec)", approved: 2001,
    dosage: "400–600 mg once daily with food",
    description: "Targeted BCR-ABL tyrosine kinase inhibitor revolutionizing CML treatment. First targeted cancer therapy.",
    symptoms: ["chronic myeloid leukemia (CML)", "GIST", "Ph+ ALL", "myelodysplastic syndromes"],
    effects: ["edema", "nausea", "muscle cramps", "diarrhea", "hepatotoxicity", "cardiac dysfunction", "myelosuppression"],
    contraindications: ["severe hepatic impairment", "pregnancy (teratogenic)"],
    interactions: ["CYP3A4 inhibitors/inducers", "warfarin", "simvastatin", "acetaminophen (hepatotoxicity)"],
    sentiment: "positive",
  },
  {
    id: 46, category: "Oncology",
    name: "Dexamethasone", genericName: "Dexamethasone",
    reviews: 1120, suitability: 69, rating: 3.7, risk: "HIGH",
    manufacturer: "Various (generic)", approved: 1958,
    dosage: "0.5–20 mg daily; 40 mg/week (hematologic malignancies)",
    description: "Potent synthetic corticosteroid used in oncology for CINV, brain edema, and hematologic malignancy treatment.",
    symptoms: ["cerebral edema", "CINV", "multiple myeloma", "ALL", "allergic reactions", "COVID-19 severe disease"],
    effects: ["severe immunosuppression", "hyperglycemia", "osteoporosis", "avascular necrosis", "psychosis", "adrenal suppression"],
    contraindications: ["systemic fungal infection", "live vaccines"],
    interactions: ["NSAIDs", "antidiabetics", "anticoagulants", "phenytoin (reduced effect)", "live vaccines"],
    sentiment: "neutral",
  },

  /* ── NEUROLOGICAL ────────────────────────────────────────── */
  {
    id: 47, category: "Neurological",
    name: "Levodopa / Carbidopa", genericName: "Carbidopa-Levodopa",
    reviews: 1430, suitability: 78, rating: 4.0, risk: "MEDIUM",
    manufacturer: "Merck (Sinemet)", approved: 1975,
    dosage: "25/100 mg three times daily (titrate)",
    description: "Gold-standard treatment for Parkinson's disease. Levodopa replaces dopamine; carbidopa prevents peripheral conversion.",
    symptoms: ["Parkinson's disease", "motor fluctuations", "restless legs syndrome (low dose)", "parkinsonism"],
    effects: ["dyskinesia", "nausea", "postural hypotension", "on-off fluctuations", "hallucinations", "impulse control disorders"],
    contraindications: ["MAOIs", "narrow-angle glaucoma", "undiagnosed skin lesions (melanoma risk)"],
    interactions: ["MAOIs", "antipsychotics (antagonism)", "iron supplements (absorption)", "pyridoxine (vitamin B6)"],
    sentiment: "positive",
  },
  {
    id: 48, category: "Neurological",
    name: "Gabapentin", genericName: "Gabapentin",
    reviews: 2870, suitability: 74, rating: 3.8, risk: "MEDIUM",
    manufacturer: "Pfizer (Neurontin)", approved: 1993,
    dosage: "300–3600 mg daily in three divided doses",
    description: "Anticonvulsant and neuropathic pain agent. Acts on voltage-gated calcium channels.",
    symptoms: ["epilepsy (partial seizures)", "neuropathic pain", "postherpetic neuralgia", "fibromyalgia", "restless legs"],
    effects: ["somnolence", "dizziness", "ataxia", "weight gain", "edema", "respiratory depression (with opioids)", "abuse potential"],
    contraindications: ["hypersensitivity", "respiratory depression risk with opioids or CNS depressants"],
    interactions: ["opioids (CNS/respiratory depression)", "alcohol", "antacids (absorption)", "CNS depressants"],
    sentiment: "neutral",
  },
  {
    id: 49, category: "Neurological",
    name: "Phenytoin", genericName: "Phenytoin Sodium",
    reviews: 890, suitability: 66, rating: 3.5, risk: "HIGH",
    manufacturer: "Pfizer (Dilantin)", approved: 1953,
    dosage: "4–7 mg/kg/day (serum level 10–20 mcg/mL)",
    description: "First-generation anticonvulsant for tonic-clonic and focal seizures. Complex pharmacokinetics requiring monitoring.",
    symptoms: ["tonic-clonic seizures", "status epilepticus", "trigeminal neuralgia", "seizure prophylaxis (head injury)"],
    effects: ["gingival hyperplasia", "hirsutism", "ataxia", "cognitive impairment", "teratogenicity", "Stevens-Johnson syndrome"],
    contraindications: ["sinus bradycardia", "sinoatrial block", "hypersensitivity to hydantoins", "pregnancy"],
    interactions: ["highly interacting — CYP2C9/CYP3A4", "warfarin", "oral contraceptives", "carbamazepine", "valproate"],
    sentiment: "negative",
  },
  {
    id: 50, category: "Neurological",
    name: "Sumatriptan", genericName: "Sumatriptan Succinate",
    reviews: 2140, suitability: 83, rating: 4.1, risk: "LOW",
    manufacturer: "GlaxoSmithKline (Imitrex)", approved: 1992,
    dosage: "50–100 mg oral at onset; repeat after 2 hr if needed, max 200 mg/day",
    description: "Selective 5-HT1B/1D agonist triptan for acute migraine and cluster headache treatment.",
    symptoms: ["migraine with/without aura", "cluster headaches", "acute migraine attack"],
    effects: ["chest tightness", "tingling", "flushing", "somnolence", "medication-overuse headache", "rare: coronary vasospasm"],
    contraindications: ["coronary artery disease", "uncontrolled hypertension", "hemiplegic migraine", "MAOIs within 2 weeks"],
    interactions: ["MAOIs", "SSRIs (serotonin syndrome)", "ergotamines (vasoconstriction)", "lithium"],
    sentiment: "positive",
  },

  /* ── IMMUNOSUPPRESSANTS ──────────────────────────────────── */
  {
    id: 51, category: "Immunosuppressants",
    name: "Azathioprine", genericName: "Azathioprine",
    reviews: 870, suitability: 67, rating: 3.6, risk: "HIGH",
    manufacturer: "GlaxoSmithKline (Imuran)", approved: 1968,
    dosage: "1–3 mg/kg/day",
    description: "Purine analog immunosuppressant for autoimmune diseases and organ transplant rejection prevention.",
    symptoms: ["organ transplant rejection prevention", "rheumatoid arthritis", "Crohn's disease", "lupus", "myasthenia gravis"],
    effects: ["myelosuppression", "hepatotoxicity", "increased infection risk", "nausea", "lymphoma risk", "teratogenicity"],
    contraindications: ["TPMT deficiency (severe toxicity)", "concurrent allopurinol (without dose reduction)", "pregnancy"],
    interactions: ["allopurinol (4× toxicity)", "warfarin", "ACE inhibitors", "mesalazine"],
    sentiment: "negative",
  },
  {
    id: 52, category: "Immunosuppressants",
    name: "Cyclosporine", genericName: "Cyclosporin A",
    reviews: 640, suitability: 61, rating: 3.5, risk: "HIGH",
    manufacturer: "Novartis (Sandimmune)", approved: 1983,
    dosage: "10–15 mg/kg/day (transplant); 2.5–5 mg/kg (autoimmune)",
    description: "Calcineurin inhibitor immunosuppressant critical for transplant medicine. Very narrow therapeutic index.",
    symptoms: ["organ transplantation", "rheumatoid arthritis", "psoriasis", "atopic dermatitis", "uveitis"],
    effects: ["nephrotoxicity", "hypertension", "tremor", "hirsutism", "gingival hyperplasia", "lymphoma risk", "neurotoxicity"],
    contraindications: ["abnormal renal function", "uncontrolled hypertension", "live vaccines"],
    interactions: [">100 documented interactions", "NSAIDs (nephrotoxicity)", "statins (myopathy)", "grapefruit (elevated levels)"],
    sentiment: "negative",
  },
  {
    id: 53, category: "Immunosuppressants",
    name: "Hydroxychloroquine", genericName: "Hydroxychloroquine Sulfate",
    reviews: 2340, suitability: 81, rating: 4.1, risk: "LOW",
    manufacturer: "Sanofi (Plaquenil)", approved: 1955,
    dosage: "200–400 mg daily (≤5 mg/kg/day lean body weight)",
    description: "Antimalarial and immunomodulator for lupus and rheumatoid arthritis. Long-term safety profile.",
    symptoms: ["systemic lupus erythematosus", "rheumatoid arthritis", "malaria prophylaxis", "Sjögren's syndrome", "dermatomyositis"],
    effects: ["retinopathy (long-term)", "nausea", "skin pigmentation", "QT prolongation", "headache"],
    contraindications: ["retinal disease", "hypersensitivity to 4-aminoquinolines", "G6PD deficiency (hemolysis)"],
    interactions: ["QT-prolonging drugs", "digoxin", "cyclosporine", "mefloquine"],
    sentiment: "positive",
  },

  /* ── ANTICOAGULANTS ─────────────────────────────────────── */
  {
    id: 54, category: "Anticoagulants",
    name: "Rivaroxaban", genericName: "Rivaroxaban",
    reviews: 1870, suitability: 78, rating: 4.0, risk: "MEDIUM",
    manufacturer: "Bayer / Janssen (Xarelto)", approved: 2011,
    dosage: "10–20 mg once daily with food",
    description: "Direct oral anticoagulant (DOAC) — factor Xa inhibitor. No routine monitoring required.",
    symptoms: ["DVT treatment/prevention", "PE treatment", "atrial fibrillation stroke prevention", "ACS"],
    effects: ["bleeding risk", "anemia", "nausea", "wound bleeding", "spinal hematoma (neuraxial risk)"],
    contraindications: ["active pathological bleeding", "hepatic disease with coagulopathy", "mechanical heart valves", "pregnancy"],
    interactions: ["strong CYP3A4/P-gp inhibitors (azoles, HIV PIs)", "rifampin (reduced effect)", "NSAIDs", "other anticoagulants"],
    sentiment: "positive",
  },
  {
    id: 55, category: "Anticoagulants",
    name: "Apixaban", genericName: "Apixaban",
    reviews: 1640, suitability: 80, rating: 4.1, risk: "MEDIUM",
    manufacturer: "Bristol-Myers Squibb / Pfizer (Eliquis)", approved: 2012,
    dosage: "5 mg twice daily (2.5 mg if ≥2 dose-reduction criteria)",
    description: "Direct factor Xa inhibitor DOAC with lowest bleeding profile among DOACs. Preferred in elderly.",
    symptoms: ["atrial fibrillation", "DVT/PE treatment and prevention", "post-surgical VTE prophylaxis"],
    effects: ["bleeding", "bruising", "anemia", "nausea", "hypersensitivity reactions"],
    contraindications: ["active bleeding", "severe hepatic impairment", "mechanical heart valves", "pregnancy"],
    interactions: ["strong CYP3A4 / P-gp inhibitors or inducers", "rifampin", "NSAIDs", "antiplatelet agents"],
    sentiment: "positive",
  },
  {
    id: 56, category: "Anticoagulants",
    name: "Heparin", genericName: "Unfractionated Heparin",
    reviews: 780, suitability: 70, rating: 3.8, risk: "HIGH",
    manufacturer: "Various (generic)", approved: 1935,
    dosage: "IV infusion (aPTT-guided); 5000 units SC BD (prophylaxis)",
    description: "Parenteral anticoagulant for immediate anticoagulation in hospital settings. Reversible with protamine.",
    symptoms: ["DVT/PE (acute)", "ACS", "atrial fibrillation", "extracorporeal circulation", "DIC treatment"],
    effects: ["HIT (immune thrombocytopenia)", "bleeding", "osteoporosis (long-term)", "hyperkalemia", "liver enzyme elevation"],
    contraindications: ["active bleeding", "HIT history", "severe thrombocytopenia", "intracranial hemorrhage"],
    interactions: ["antiplatelet drugs", "thrombolytics", "NSAIDs", "dextran"],
    sentiment: "neutral",
  },

  /* ── EXTRA MISCELLANEOUS ─────────────────────────────────── */
  {
    id: 57, category: "Pain & Inflammation",
    name: "Morphine", genericName: "Morphine Sulfate",
    reviews: 870, suitability: 58, rating: 3.4, risk: "HIGH",
    manufacturer: "Various (generic)", approved: 1827,
    dosage: "5–15 mg oral every 4 hours (IR); adjust per response",
    description: "Prototype opioid analgesic for severe pain. High dependence and abuse potential.",
    symptoms: ["severe acute pain", "cancer pain", "post-operative pain", "dyspnea in palliative care", "myocardial infarction pain"],
    effects: ["respiratory depression", "constipation", "nausea", "sedation", "dependence", "pruritus", "urinary retention"],
    contraindications: ["severe respiratory depression", "paralytic ileus", "acute asthma", "concurrent MAOIs"],
    interactions: ["alcohol", "benzodiazepines (fatal)", "CNS depressants", "MAOIs", "antipsychotics"],
    sentiment: "negative",
  },
  {
    id: 58, category: "Cardiovascular",
    name: "Clopidogrel", genericName: "Clopidogrel Bisulfate",
    reviews: 2140, suitability: 79, rating: 4.0, risk: "MEDIUM",
    manufacturer: "Sanofi / BMS (Plavix)", approved: 1997,
    dosage: "75 mg once daily (loading dose 300–600 mg)",
    description: "P2Y12 ADP receptor antiplatelet agent for ACS, MI, and stent thrombosis prevention.",
    symptoms: ["acute coronary syndrome", "MI (post)", "ischemic stroke", "PCI/stent thrombosis prevention", "PAD"],
    effects: ["bleeding", "bruising", "rash", "TTP (rare)", "GI upset"],
    contraindications: ["active pathological bleeding", "CYP2C19 poor metabolizers (reduced efficacy)", "peptic ulcer"],
    interactions: ["PPIs (reduced effect via CYP2C19)", "NSAIDs", "warfarin", "aspirin (used together in ACS)"],
    sentiment: "positive",
  },
  {
    id: 59, category: "Antibiotics",
    name: "Trimethoprim-Sulfamethoxazole", genericName: "Co-trimoxazole",
    reviews: 1780, suitability: 79, rating: 3.9, risk: "MEDIUM",
    manufacturer: "Roche (Bactrim)", approved: 1968,
    dosage: "1 DS tablet (160/800 mg) twice daily",
    description: "Combination antibiotic for UTIs, pneumocystis pneumonia, MRSA soft tissue infections, and toxoplasmosis.",
    symptoms: ["uncomplicated UTI", "PCP pneumonia", "MRSA skin infections", "toxoplasmosis", "traveler's diarrhea"],
    effects: ["rash", "Stevens-Johnson syndrome (rare)", "hyperkalemia", "photosensitivity", "nausea", "bone marrow suppression"],
    contraindications: ["sulfonamide allergy", "severe renal/hepatic impairment", "pregnancy (third trimester)", "G6PD deficiency"],
    interactions: ["warfarin (increased effect)", "methotrexate (toxicity)", "ACE inhibitors (hyperkalemia)", "phenytoin"],
    sentiment: "neutral",
  },
  {
    id: 60, category: "Respiratory",
    name: "Prednisone", genericName: "Prednisone",
    reviews: 2340, suitability: 74, rating: 3.8, risk: "MEDIUM",
    manufacturer: "Various (generic)", approved: 1955,
    dosage: "5–60 mg daily (condition-dependent)",
    description: "Oral corticosteroid for acute asthma exacerbations, COPD exacerbations, and inflammatory conditions.",
    symptoms: ["acute asthma exacerbation", "COPD exacerbation", "allergic reactions", "inflammatory conditions", "adrenal insufficiency"],
    effects: ["hyperglycemia", "weight gain", "mood changes", "insomnia", "GI upset", "adrenal suppression", "infection risk"],
    contraindications: ["systemic fungal infection", "live vaccines", "hypersensitivity"],
    interactions: ["NSAIDs", "antidiabetics", "vaccines", "anticoagulants", "CYP3A4 inducers"],
    sentiment: "neutral",
  },
  {
    id: 61, category: "Mental Health",
    name: "Venlafaxine", genericName: "Venlafaxine HCl",
    reviews: 2650, suitability: 77, rating: 3.9, risk: "MEDIUM",
    manufacturer: "Wyeth / Pfizer (Effexor)", approved: 1993,
    dosage: "75–225 mg once daily (ER)",
    description: "SNRI antidepressant for depression, GAD, social anxiety, and panic disorder.",
    symptoms: ["major depression", "generalized anxiety disorder", "social anxiety disorder", "panic disorder", "PTSD", "fibromyalgia"],
    effects: ["nausea", "sweating", "sexual dysfunction", "hypertension", "discontinuation syndrome", "insomnia"],
    contraindications: ["MAOIs", "hypersensitivity", "uncontrolled narrow-angle glaucoma"],
    interactions: ["MAOIs", "tramadol", "triptans", "linezolid", "methylene blue", "lithium"],
    sentiment: "neutral",
  },
  {
    id: 62, category: "Diabetes",
    name: "Liraglutide", genericName: "Liraglutide",
    reviews: 1340, suitability: 83, rating: 4.2, risk: "LOW",
    manufacturer: "Novo Nordisk (Victoza/Saxenda)", approved: 2010,
    dosage: "0.6–1.8 mg SC once daily (diabetes); up to 3 mg (obesity)",
    description: "GLP-1 receptor agonist with cardiovascular benefits, weight loss, and glycemic control for T2D and obesity.",
    symptoms: ["type 2 diabetes", "obesity/overweight with comorbidities", "cardiovascular risk reduction", "NAFLD"],
    effects: ["nausea", "vomiting", "diarrhea", "pancreatitis (rare)", "thyroid C-cell tumors (rodents)", "injection site reactions"],
    contraindications: ["personal/family history of medullary thyroid cancer", "MEN2", "diabetic gastroparesis"],
    interactions: ["insulin/sulfonylureas (hypoglycemia)", "oral medications (delayed gastric emptying)"],
    sentiment: "positive",
  },
  {
    id: 63, category: "Cardiovascular",
    name: "Spironolactone", genericName: "Spironolactone",
    reviews: 1890, suitability: 77, rating: 3.9, risk: "MEDIUM",
    manufacturer: "Various (generic, Aldactone)", approved: 1960,
    dosage: "25–400 mg daily",
    description: "Aldosterone antagonist for heart failure, hypertension, hyperaldosteronism, and female acne/hirsutism.",
    symptoms: ["heart failure", "hypertension", "primary hyperaldosteronism", "acne (female)", "hirsutism", "edema"],
    effects: ["hyperkalemia", "gynecomastia (men)", "menstrual irregularities", "dizziness", "breast tenderness"],
    contraindications: ["Addison's disease", "hyperkalemia", "severe renal impairment", "anuria"],
    interactions: ["ACE inhibitors (hyperkalemia)", "NSAIDs (reduced effect)", "digoxin (increased levels)", "lithium"],
    sentiment: "positive",
  },
  {
    id: 64, category: "Gastrointestinal",
    name: "Ranitidine", genericName: "Ranitidine HCl",
    reviews: 1240, suitability: 80, rating: 4.0, risk: "LOW",
    manufacturer: "GlaxoSmithKline (withdrawn 2020)", approved: 1983,
    dosage: "150 mg twice daily or 300 mg at night",
    description: "H2 receptor antagonist for peptic ulcer and GERD. Largely replaced by PPIs. Withdrawn due to NDMA concerns.",
    symptoms: ["peptic ulcer disease", "GERD", "Zollinger-Ellison syndrome", "NSAID-induced ulcer prevention"],
    effects: ["headache", "diarrhea", "constipation", "dizziness", "NDMA contamination concern (withdrawal reason)"],
    contraindications: ["porphyria", "phenylketonuria (effervescent)", "renal impairment (dose adjust)"],
    interactions: ["warfarin", "triazolam", "antacids (absorption)", "glipizide"],
    sentiment: "neutral",
  },
];

/* Computed aggregates used across the app */
export const TOTAL_REVIEWS = MEDICINES_DB.reduce((s, m) => s + m.reviews, 0);
export const LOW_COUNT     = MEDICINES_DB.filter(m => m.risk === "LOW").length;
export const MEDIUM_COUNT  = MEDICINES_DB.filter(m => m.risk === "MEDIUM").length;
export const HIGH_COUNT    = MEDICINES_DB.filter(m => m.risk === "HIGH").length;

export const RISK_PIE_DATA = [
  { name: "Low Risk",    value: LOW_COUNT,    color: "#22c55e" },
  { name: "Medium Risk", value: MEDIUM_COUNT, color: "#f59e0b" },
  { name: "High Risk",   value: HIGH_COUNT,   color: "#ef4444" },
];

/* Top symptoms across all medicines (for bar chart) */
const symFreq = {};
MEDICINES_DB.forEach(m =>
  m.symptoms.forEach(s => {
    const key = s.split(" ").slice(0, 2).join(" ");
    symFreq[key] = (symFreq[key] || 0) + 1;
  })
);
export const SYMPTOM_FREQ_DATA = Object.entries(symFreq)
  .sort((a, b) => b[1] - a[1])
  .slice(0, 10)
  .map(([name, count]) => ({ name: name.charAt(0).toUpperCase() + name.slice(1), count }));

/* Per-category counts for analytics */
export const CATEGORY_DATA = MEDICINE_CATEGORIES.map(cat => ({
  name: cat.split(" ")[0],
  fullName: cat,
  count: MEDICINES_DB.filter(m => m.category === cat).length,
  avgSuitability: Math.round(
    MEDICINES_DB.filter(m => m.category === cat).reduce((s, m) => s + m.suitability, 0) /
    (MEDICINES_DB.filter(m => m.category === cat).length || 1)
  ),
  totalReviews: MEDICINES_DB.filter(m => m.category === cat).reduce((s, m) => s + m.reviews, 0),
}));